stages:
  - build
  - release
  
image: maven:3.6-jdk-8-slim

variables:
  GIT_SUBMODULE_STRATEGY: normal
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=.m2/repository"  
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version"
  
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .m2/repository
  
build_maven:
  stage: build
  only:
  - develop
  - branches
  script:
  - mvn $MAVEN_CLI_OPTS deploy -DskipTests
  artifacts:
    paths:
    - target/*.jar
    expire_in: 1 hour
  
release_tag:
  stage: release
  only:
  - tags
  script:
  - echo "Versión del tag $CI_COMMIT_TAG"
  - mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=$CI_COMMIT_TAG
  - mvn $MAVEN_CLI_OPTS deploy -DskipTests
  artifacts:
    paths:
    - target/*.jar
    expire_in: 1 hour  
    
